---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
b<-"你好"
bVector<-c("你好","How are you?")
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
dialogue <- c('小明說：'明天不用上課。',
               '小花說:'真的嗎？')

cat(dialogue, sep='\n')
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
sum(aLogical)

```{r}
#factor
```


```{r}
studentMajors <- (
  c("經濟系", "經濟系", "法律系")
)
```


```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```
```{r}
studentMajors
```

```{r}
as.integer(studentMajors)
```

```{r}
class(studentMajors)
```


```{r}
birthplace <- factor(
    c("台北市","新北市","台中市","台南市","高雄市") )
```

```{r}
#install.packages("tidyverse")
```

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```
```{r}
tObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```
```{r}
dtObject
```


```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) 
